---
# tasks for uploading database dump and loading into database

- name: copy database dump from local machine
  copy: src={{ item }} dest=/{{ install_dir }}/otindex.dmp
  with_fileglob:
      - "{{ database_dump_filename }}"

# clear the existing data
- name: clear database tables
  command: $VENV/bin/python otindex/scripts/setup_db.py {{ config_filename }}
  environment:
    VENV: "{{ install_dir }}/venv"
  args:
    chdir: "{{ install_dir }}/otindex"

# load the database dump into the database
- name: load database dump
  become: true
  become_user: postgres
  command: pg_restore -a --verbose --dbname=otindex  /{{ install_dir }}/otindex.dmp
