---
# tasks for uploading database dump and loading into database

#Copies database, but doesn't seem to actually work... I SCP'd it directly.
- name: copy database dump from local machine
  copy: src={{ item }} dest={{ install_dir }}/otindex/otindex.dmp
  with_fileglob:
      - "{{ database_dump_filename }}"
  become: true

#remove the existing database
- name: load database dump
  become: true
  become_user: postgres
  command: dropdb otindex


# load the database dump into the database
- name: load database dump
  become: true
  become_user: postgres
  command: psql otindex < "{{ install_dir }}/otindex/otindex.dmp"
