---
- hosts: all

# start by installing required packages (note that postgresql packages
# installed separately in postgresql role)
  pre_tasks:
    - name: Install packages
      become: true
      apt: name={{ item }} state=present
      with_items:
        - virtualenv
        - libpq-dev
        - git-core
        - python-psycopg2
        - build-essential
        - python-dev

  roles:
    - postgresql
    - peyotl
    - otindex
    - otdata
    - apache

  # set this at play level because used multiple roles: peyotl and otindex
  environment:
      PEYOTL_CONFIG_FILE: "{{ peyotl_config_location }}/config"

  handlers:
      - name: restart apache
        become: true
        service: name=apache2 state=restarted
