---
- hosts: all

# start by installing required packages (note that postgresql packages
# installed separately in postgresql role)
  pre_tasks:
    - name: Install packages
      become: true
      apt: name={{ item }} state=present
      with_items:
        - virtualenv
        - libpq-dev
        - apache2
        - libapache2-mod-wsgi
        - git-core
        - python-psycopg2
        - build-essential
        - python-dev

  roles:
    - otdata
    - postgresql

  tasks:

  # otindex setup
  - name: Clone otindex repo
    git: repo=https://github.com/OpenTreeOfLife/otindex.git dest=/home/rapiduser/otindex

  - name: Install otindex python requirements
    pip: requirements=/home/rapiduser/otindex/requirements.txt virtualenv=/home/rapiduser/otindex/venv
